mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSW0RD:123456}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL:localhost:3307}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none