version: '3.7'

services:
#  app:
#    container_name: adm_videos_app
##    image: fabsouza/fc-catalog-admin:main-3
#    build: .
#    profiles: ["app"]
#    restart: unless-stopped
#    env_file:
#      - .env.local
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysql
#      - rabbit
#    networks:
#      - adm_videos_network

  mysql:
    container_name: adm_videos_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adm_videos
      MYSQL_ROOT_HOST: '%'
    security_opt:
      - seccomp:unconfined
    ports:
      - 3307:3306
    volumes:
      - .docker/mysql:/var/lib/mysql:rw
    networks:
      - adm_videos_network

  rabbit:
    container_name: adm_videos_rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=adm_videos
      - RABBITMQ_DEFAULT_PASS=123456
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - adm_videos_network

  keycloak:
    container_name: adm_videos_keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8443:8080
    command:
      - start-dev # Utilizar esse comando quando a aplicação estiver executando fora do Docker
#      - start-dev --hostname-url=http://keycloak:8080 # Utilizar esse comando quando a aplicação estiver dentro do Docker
    volumes:
      - .docker/keycloak:/opt/keycloak/data/h2:rw
    networks:
      - adm_videos_network

networks:
  adm_videos_network: